# Generated by Django 4.0.3 on 2022-04-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='bridge_chord_prog',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='chorus',
            name='chorus_chord_prog',
            field=models.CharField(blank=True, max_length=360),
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse_chord_prog',
            field=models.CharField(blank=True, max_length=360),
        ),
    ]
